
# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY!
# The file contains the precomputed change of basis and irreps_out
# for reasonable combinations of irreps in Graph2Mat, to avoid the
# very expensive initialization of e3nn.o3.ReducedTensorProducts

ALL_RTPS = {}